### PR TITLE
wait for discord initialized to update presence (fix #294)

### LINKED ISSUE #294: Discord -> Main Menu status not working
The Main Menu status no longer displays unless you change to a map and then disconnect. The live version on steam behaves correctly. 

d1
d2

### PR DESCRIPTION
**Pull request by CoolElectronics**

### CODE REVIEW

File: source/client/cl_presence.c [hunk 1]
```diff
@@ -596,8 +596,7 @@ static const char *CL_PlayerStatus( snapshot_t *frame )
 
 void CL_UpdatePresence( void )
 {
-	// is there a better way of checking whether steam is ready?
-	if( cl_presence_state.discord_initialized || Steam_Active()) {
```
Comment (pollend) [inline source/client/cl_presence.c:600]: what did you find?

**Review by pollend — APPROVED** [review]

File: source/client/cl_presence.c (hunk 1 above)
Comment (Warfork) [reply source/client/cl_presence.c:600]: The problem is the "Main Menu" "Ready to Fork" discord status doesn't appear unless you connect and disconnect from a server. After he removed removing Steam_Active() if Discord isn't running then Steam will no longer have status updates.

Comment (CoolElectronics) [reply source/client/cl_presence.c:600]: > what did you find?

the comment was made before i had rewritten steamshim, it had different behavior then
